<a href="https://colab.research.google.com/github/Shofia09/cupi-s-project/blob/Determining-maturity-level-of-Crystal-Guava-Based-on-HSI-Color-Space/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Klasifikasi Tingkat Kematangan**

Berdasarkan warna HSI yang diperoleh dari citra buah jambu kristal dalam proses [pengolahan citra](https://colab.research.google.com/drive/1q99ChhSbiL0nG23IhTzrpeYgbQorxL9T#scrollTo=aeSgzzp2KXl-), tingkat kematangan buah dapat ditentukan menggunakan metode klasifikasi yang tepat. Metode jaringan saraf tiruan Backpropagation merupakan salah satu metode klasifikasi yang menyerupai cara kerja otak manusia dimana permasalahan diselesaikan dengan pembelajaran atau pelatihan terhadap jaringan. Jaringan saraf tiruan Backpropagation banyak digunakan untuk menyelesaikan permasalahan pengenalan pola, salah satunya yaitu klasifikasi


In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.utils import to_categorical

#memanggil data
data=pd.read_excel("/content/drive/MyDrive/Data/ekstraksihsi.xlsx")
data=pd.DataFrame(data,columns=['H','S','I','Kelas'])

#normalisasi H
scaler = MinMaxScaler()
H=np.array(data['H'])
H = H.reshape(-1, 1) #mengubah array 1D to 2D
scaled_data = scaler.fit_transform(H)
data['H']=scaled_data #mengganti nilai H

print(data)
#memisahkan data dan target
x_train=data.iloc[0:120,0:3].values #variabel x
train=data.iloc[0:120,3].values #variabel y
x_test=data.iloc[120:140,0:3].values #variabel x
test=data.iloc[120:140,3].values #variabel y
y_train = to_categorical(train)
y_test = to_categorical(test)
print(x_train)
print(y_train)
print(x_test)
print(y_test)
print((y_train.shape))

            H         S         I  Kelas
0    0.707873  0.381377  0.241658      2
1    0.650493  0.452647  0.184040      2
2    0.674064  0.606033  0.152268      2
3    0.712742  0.425701  0.162684      2
4    0.677121  0.494961  0.332355      2
..        ...       ...       ...    ...
135  0.700377  0.500998  0.263201      1
136  0.566802  0.566269  0.280161      1
137  0.683127  0.630708  0.309829      1
138  0.680675  0.531452  0.263420      1
139  0.711636  0.536518  0.304840      1

[140 rows x 4 columns]
[[0.70787311 0.38137687 0.2416581 ]
 [0.65049284 0.45264655 0.18403977]
 [0.6740643  0.60603265 0.15226827]
 [0.71274192 0.4257011  0.16268395]
 [0.6771214  0.4949606  0.33235497]
 [0.59616701 0.60502846 0.23450958]
 [0.68699061 0.47919017 0.20595546]
 [0.679091   0.49639926 0.2645151 ]
 [0.69322502 0.47904467 0.23028131]
 [0.65964954 0.67988993 0.22594771]
 [0.5890588  0.67163147 0.19469516]
 [0.         0.61656809 0.09545755]
 [0.64020181 0.51325206 0.23486167]
 [0.69302193 0.5

In [ ]:
import numpy as np
import tensorflow as tf #backpropagation
from tensorflow import keras

hidden=10
alpha=0.3
epochs=1500

# Membuat model arsitektur
model = tf.keras.models.Sequential()
# Inisialisasi bobot
weight1 = np.random.rand(3, hidden)
weight2 = np.random.rand(hidden, 4)
init1 = tf.constant_initializer(weight1)
init2 = tf.constant_initializer(weight2)
model.add(tf.keras.layers.Dense(units=hidden, activation='sigmoid', input_dim=3, kernel_initializer=init1)) #hidden layer
model.add(tf.keras.layers.Dense(units=4, activation='sigmoid', kernel_initializer=init2)) #output layer

opt = keras.optimizers.Adam(learning_rate=alpha)
model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])

print('training')
model.fit(x_train,y_train,epochs=epochs,batch_size=64)


training
Epoch 1/1500
2/2 [==============================] - 1s 8ms/step - loss: 1.7469 - accuracy: 0.2583
Epoch 2/1500
2/2 [==============================] - 0s 10ms/step - loss: 1.9640 - accuracy: 0.2500
Epoch 3/1500
2/2 [==============================] - 0s 7ms/step - loss: 1.4381 - accuracy: 0.2167
Epoch 4/1500
2/2 [==============================] - 0s 7ms/step - loss: 1.4841 - accuracy: 0.2500
Epoch 5/1500
2/2 [==============================] - 0s 7ms/step - loss: 1.4583 - accuracy: 0.2500
Epoch 6/1500
2/2 [==============================] - 0s 7ms/step - loss: 1.4169 - accuracy: 0.2500
Epoch 7/1500
2/2 [==============================] - 0s 13ms/step - loss: 1.3980 - accuracy: 0.2917
Epoch 8/1500
2/2 [==============================] - 0s 7ms/step - loss: 1.3951 - accuracy: 0.2083
Epoch 9/1500
2/2 [==============================] - 0s 7ms/step - loss: 1.4000 - accuracy: 0.2417
Epoch 10/1500
2/2 [==============================] - 0s 7ms/step - loss: 1.3998 - accuracy: 0.2500
Epoch 11

In [ ]:
print('testing')
model.evaluate(x_test,y_test,batch_size=32)

testing
1/1 [==============================] - 0s 275ms/step - loss: 0.6308 - accuracy: 0.9000


[0.6308094263076782, 0.8999999761581421]

In [ ]:
import os
import pandas as pd

w1 = pd.DataFrame(weight1)
w2 = pd.DataFrame(weight2)

path = "/content/drive/MyDrive/Data"
# Save the weight
output_path = os.path.join(path, 'bobot1.xlsx')
#w1.to_excel(output_path, index=False)
output_path = os.path.join(path, 'bobot2.xlsx')
#w2.to_excel(output_path, index=False)


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
weightb1 = np.random.rand(1, 10)
weightb2 = np.random.rand(1, 4)
print(weightb1)
print(weightb2)

In [ ]:
import os

#menyimpan model
nameFile = "model" + str(epochs) + "_" + str(hidden) + "_" + str(alpha) + ".h5"
model_path = "/content/drive/MyDrive/Colab Notebooks/SKRIPSI/SAVE MODEL/"

# Save the model
output_path = os.path.join(model_path, nameFile)
#model.save = model.save(output_path)
print(nameFile)

In [ ]:
from sklearn import metrics

#Metrik evaluasi testing
pred = model.predict(x_test)
pred = np.argmax(pred, axis=1)
print(pred)
print(test)

average = 'weighted'
Accuracy = metrics.accuracy_score(test, pred)
Precision = metrics.precision_score(test, pred, average=average)
Recall = metrics.recall_score(test, pred, average=average)
F1_score = metrics.f1_score(test, pred, average=average)

#metrics
print({"Accuracy":Accuracy,"Precision":Precision,"Recall":Recall,"F1_score":F1_score})

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(pred,test)

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.ylabel('Prediction',fontsize=13)
plt.xlabel('Actual',fontsize=13)
plt.title('Confusion Matrix',fontsize=17)
plt.show()